export const ROOT_URL = "https://rickandmortyapi.com/api";
export const REQUEST_CHARACTERS_LIST = "REQUEST_CHARACTERS_LIST";
export const RECEIVE_CHARACTERS_LIST = "RECEIVE_CHARACTERS_LIST";
export const ERROR_CHARACTERS = "ERROR_CHARACTERS";
export const REQUEST_CHARACTER = "REQUEST_CHARACTER";
export const RECEIVE_CHARACTER = "RECEIVE_CHARACTER";
